### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Kuekua** [hejingwenhejingwen/CResMD#1]
Hi, can you share the source code? Thanks

**Comment by hejingwenhejingwen** [comment]
I will release the code within one month.
Thanks!

**Comment by oneTaken** [comment]
@hejingwenhejingwen three month pass by., will you release the source code?

**Comment by dorbarber79** [comment]
hi. it will be great if you could release the code in your paper

**Comment by dexception** [comment]
Waiting for the source code

**Comment by hejingwenhejingwen** [comment]
Sorry to keep you waiting. Now I have released the code, and please help to check. Thanks.
