### ISSUE TITLE
Will the 3D pretrained-model be released?

### ISSUE THREAD

**Issue by splinter21** [hejingwenhejingwen/CResMD#2]
deblock+denoise+deblur

Also I want to reprocude the model by other (our own) dataset. 
How to make the noise/blur/jpeg artifact?
What is the sequence? And what are the level range of these three processes? What kind of noise/blur should we use?

**Comment by hejingwenhejingwen** [comment]
Please refer to [`codes/data_scripts/generate_2groups.m`](https://github.com/hejingwenhejingwen/CResMD/blob/master/codes/data_scripts/generate_2groups.m) and [`codes/data_scripts/generate_3groups.m`](https://github.com/hejingwenhejingwen/CResMD/blob/master/codes/data_scripts/generate_3groups.m) for details.

**Comment by hejingwenhejingwen** [comment]
[3D model](https://github.com/hejingwenhejingwen/CResMD/tree/master/experiments/pretrain_models). Sorry for my late reply.
